# Generated by Django 4.2 on 2023-04-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_agent_agentengine_agentcredentials'),
        ('ai_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DecisionTemplate',
            new_name='PromptTemplate',
        ),
    ]
