# Generated by Django 4.2 on 2023-04-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0004_alter_prompttemplate_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompttemplate',
            old_name='body',
            new_name='prompt',
        ),
    ]
