# Generated by Django 4.2 on 2023-04-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0006_rename_prompttemplate_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='ai_example',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='human_example',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
