# Generated by Django 4.2 on 2023-04-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_agent_agentengine_agentcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brief',
            field=models.TextField(blank=True, help_text='Provide a brief to help the AI understand the organization', null=True),
        ),
    ]
